name: Deploy Pages

on:
  push:
    branches:
      - main
    paths:
      - 'Site/**'
      - '.github/workflows/pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Build Site (Blazor WASM)
      run: dotnet publish Site/site.csproj -c Release -o site-output

    - name: Update base href for GitHub Pages dynamically
      run: sed -i 's|<base href="/" />|<base href="/${{ github.event.repository.name }}/" />|g' site-output/wwwroot/index.html

    - name: Add .nojekyll
      run: |
        touch site-output/wwwroot/.nojekyll

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload site artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: site-output/wwwroot

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
